---
title: "Spatial Viz"
---

Use this file to generate a professional looking **spatial** visualization.  The visualization will not perfect the first time but you are expected to improve on it throughout the semester especially after covering advanced topics such as effective viz.


```{r}
starbucks <- read.csv("https://mac-stat.github.io/data/starbucks.csv")
```

```{r}
states_map <- map_data("state")
head(states_map)
library(RColorBrewer)
starbucks_us <- starbucks |> 
  filter(Country == "US")

ggplot(starbucks_with_2018_pop_est, aes(map_id = state_name, fill = starbucks_per_10000)) +
  geom_map(map = states_map) +
  geom_point(
    data = starbucks_us,
    aes(x = Longitude, y = Latitude),
    size = 0.05,
    alpha = 0.2,
    inherit.aes = FALSE
  ) +
  expand_limits(x = states_map$long, y = states_map$lat) +
  scale_fill_gradientn(name = "Number of Starbucks", colors = c("blue", "purple", "red"), values = scales::rescale(seq(0, 100, by = 5))) +
  labs(
  title = "Starbucks Locations and Density in the Contiguous US",
  caption = "Plot created by [Isa Chen]"
)
```

